import { BgStyle } from './types/BgStyle'
import { CardStyle } from './types/CardStyle'
import { CardValue } from './types/CardValue'
import { DeckType, NemesisDeckType } from './types/DeckType'
import { createContext } from 'react'

export const DealerContext = createContext({
  baseDeck: 'twoplayer' as DeckType,
  setBaseDeck: (_: DeckType) => {},
  nemesisDeck: 'base' as NemesisDeckType,
  setNemesisDeck: (_: NemesisDeckType) => {},
  cardStyle: 'cracks' as CardStyle,
  setCardStyle: (_: CardStyle) => {},
  bgStyle: 'velvet' as BgStyle,
  setBgStyle: (_: BgStyle) => {},
  deck: [] as CardValue[],
  setDeck: (_: CardValue[]) => {},
  deckIds: [] as string[],
  setDeckIds: (_: string[] | ((prev: string[]) => string[])) => {},
  pendingShuffle: null as { deck: CardValue[], deckIds: string[], forcePeek: boolean[] } | null,
  setPendingShuffle: (_: { deck: CardValue[], deckIds: string[], forcePeek: boolean[] } | null) => {},
  deckIndex: 0,
  setDeckIndex: (_: number) => {},
  menuVisible: false as false | 'appearance' | 'composition',
  setMenuVisible: (_: false | 'appearance' | 'composition') => {},
  hapticEnabled: true,
  setHapticEnabled: (_: boolean) => {},
  isDebouncing: false,
  setIsDebouncing: (_: boolean) => {},
  editModeOn: false,
  setEditModeOn: (_: boolean) => {},
  drawCard: () => {},
  forcePeek: [] as boolean[],
  setForcePeek: (_: boolean[]) => {},
  hasFriend: false,
  setHasFriend: (_: boolean) => {},
  hasFoe: false,
  setHasFoe: (_: boolean) => {},
  intensityValue: 1,
  setIntensityValue: (_: number | ((prev: number) => number)) => {},
  history: [] as CardValue[][],
  setHistory: (_: CardValue[][] | ((prev: CardValue[][]) => CardValue[][])) => {},
  historyOpen: false,
  setHistoryOpen: (_: boolean) => {},
  endGame: () => {},
  gameSummaryOpen: false,
  setGameSummaryOpen: (_: boolean) => {},
  audioEnabled: true,
  setAudioEnabled: (_: boolean) => {},
})
